language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

sudo: false

before_install:
  - pip install -r "requirements.txt"
  - pip install -r "requirements_tests.txt"
  - pip install flake8
  - pip install coveralls

install:
  - ./setup.py install

script:
  - flake8 .
  - cd tests
  - coverage run --source=perceval run_tests.py

after_success:
  - coveralls
