language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

sudo: false

before_install:
  - pip install --upgrade setuptools==49.6.0
  - pip install --upgrade pip==18.1
  - pip install -r "requirements.txt"
  - pip install -r "requirements_tests.txt"
  - pip install flake8
  - pip install coveralls

install:
  - pip install .

script:
  - flake8 .
  - cd tests
  - coverage run --source=perceval run_tests.py

after_success:
  - coveralls
